# Generated by Django 4.1.2 on 2023-01-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pproduct',
        ),
    ]
