# Generated by Django 3.1.5 on 2022-02-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
