# Generated by Django 3.1.3 on 2021-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0003_auto_20210521_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.CharField(blank=True, default='8255', editable=False, max_length=10, unique=True),
        ),
    ]
