# Generated by Django 3.1.3 on 2021-12-16 06:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0008_auto_20210521_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
