# Generated by Django 3.1.3 on 2022-05-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0009_employee_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Phonenumber',
        ),
    ]
