# Generated by Django 3.1 on 2020-10-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
